import type { Service, Promotion, ContactInfo, SiteConfig, SocialLinks, FAQItem } from '@/types';

export const SITE_CONFIG: SiteConfig = {
  name: "Clínica Hispana La Caridad",
  shortName: "Clínica La Caridad",
  tagline: "Atención médica profesional 100% en español",
  description: "Clínica médica hispana en Houston, TX. Atención profesional en español, sin cita previa, aceptamos pacientes con o sin seguro. Medicina familiar, exámenes de inmigración, laboratorio y más.",
  baseUrl: "https://www.chlacaridad.com",
  locale: "es-MX",
  logoUrl: "/images/logo.webp",
};

export const CONTACT_INFO: ContactInfo = {
  address: "5705 Fondren Rd STE 101",
  city: "Houston",
  state: "TX",
  zip: "77036",
  phone: "+16822597190",
  phoneFormatted: "+1 (682) 259-7190",
  email: "chlacaridad@gmail.com",
  hours: "Lunes a Sábado: 9:00 AM - 6:00 PM",
  hoursWeekday: "Lunes a Viernes: 9:00 AM - 6:00 PM",
  hoursWeekend: "Sábado: 9:00 AM - 6:00 PM",
  googleMapsUrl:
    "https://www.google.com/maps/place/Clinica+La+Caridad/@29.7187891,-95.5195062,17z/data=!3m1!4b1!4m6!3m5!1s0x8640c3151e03b997:0xd06d7e301078edf9!8m2!3d29.7187891!4d-95.5195062!16s%2Fg%2F11wp4j3qbh",
  googleMapsEmbed: `https://www.google.com/maps/embed/v1/place?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_EMBED_KEY}&q=Clinica+La+Caridad+5705+Fondren+Rd+Houston+TX+77036&center=29.7187891,-95.5195062&zoom=17`,
  googleReviewUrl:
    "https://www.google.com/maps/place/Clinica+La+Caridad/@29.7187891,-95.5195062,17z/data=!3m1!4b1!4m6!3m5!1s0x8640c3151e03b997:0xd06d7e301078edf9!8m2!3d29.7187891!4d-95.5195062!16s%2Fg%2F11wp4j3qbh",
  placeId: "0x8640c3151e03b997:0xd06d7e301078edf9",
  coordinates: {
    lat: 29.7187891,
    lng: -95.5195062,
  },
};

export const SOCIAL_LINKS: SocialLinks = {
  facebook: "https://www.facebook.com/clinicalacaridadhoustontx",
  instagram: "https://www.instagram.com/clinicalacaridadhouston",
};

// Google Reviews data — verificar con el cliente
export const GOOGLE_REVIEWS_DATA = {
  totalReviews: 419,
  averageRating: 4.0,
  placeId: "",
};

export const SERVICES: Service[] = [
  {
    id: "medicina-familiar",
    slug: "medicina-familiar",
    title: "Medicina Familiar en Houston",
    shortTitle: "Familiar",
    description: "Médico de familia en Houston TX con atención 100% en español. Cuidado integral desde niños hasta adultos mayores, sin cita previa.",
    longDescription: "Nuestro servicio de medicina familiar en Houston ofrece atención médica completa y continua para pacientes de todas las edades, desde recién nacidos hasta adultos mayores. Como médico general en Houston TX, nos enfocamos en la prevención, diagnóstico y tratamiento de enfermedades comunes.\n\nAtendemos sin cita previa en nuestra clínica ubicada en 5705 Fondren Rd STE 101, Houston TX 77036, aceptamos pacientes con o sin seguro médico, y mantenemos un historial médico completo de cada miembro de su familia.\n\n**¿Qué incluye nuestra consulta de medicina familiar?**\n\nDurante su visita, nuestro médico realizará un examen físico completo, revisión de signos vitales (presión arterial, temperatura, peso, pulso), evaluación de síntomas actuales, y diagnóstico profesional. Si es necesario, se prescribirá medicamento y se ordenarán estudios de laboratorio con resultados el mismo día.\n\n**Condiciones que tratamos:**\n\n- Resfriados, gripe e infecciones respiratorias\n- Dolor de garganta, oído e infecciones\n- Alergias estacionales\n- Dolores musculares y articulares\n- Problemas digestivos\n- Control de presión arterial y glucosa\n- Chequeos preventivos anuales\n- Vacunas para niños y adultos\n\n**¿Por qué elegir Clínica Hispana La Caridad para medicina familiar?**\n\nNuestro equipo médico atiende 100% en español, entiende las necesidades de la comunidad hispana de Houston, y ofrece precios accesibles sin comprometer la calidad de atención. Estamos abiertos de lunes a sábado de 9:00 AM a 6:00 PM, para que pueda visitarnos cuando lo necesite sin largas esperas.",
    titleEn: "Family Medicine in Houston TX",
    descriptionEn: "Family doctor in Houston TX with 100% Spanish-speaking staff. Comprehensive care for patients of all ages — from newborns to seniors — no appointment needed.",
    longDescriptionEn: "Our family medicine practice in Houston provides complete, continuous medical care for patients of all ages, from newborns to the elderly. As a trusted general practitioner in Houston TX, we focus on prevention, diagnosis, and treatment of common illnesses and chronic conditions.\n\nWe welcome walk-in patients at our clinic located at 5705 Fondren Rd STE 101, Houston TX 77036. We accept patients with or without health insurance and maintain a complete medical history for every member of your family.\n\n**What does a family medicine visit include?**\n\nDuring your visit, our physician will perform a thorough physical examination, review your vital signs (blood pressure, temperature, weight, and pulse), assess your current symptoms, and provide a professional diagnosis. When needed, prescriptions and same-day lab orders are available on-site.\n\n**Conditions we treat:**\n\n- Colds, flu, and respiratory infections\n- Sore throat, ear infections, and sinusitis\n- Seasonal allergies\n- Muscle and joint pain\n- Digestive issues and stomach problems\n- Blood pressure and blood sugar management\n- Annual preventive checkups\n- Vaccines for children and adults\n\n**Why choose Clínica Hispana La Caridad for family medicine?**\n\nOur medical team is fully bilingual and deeply understands the needs of Houston's Hispanic community. We offer affordable, high-quality care with no long waits. We're open Monday through Saturday from 9:00 AM to 6:00 PM.",
    icon: "Stethoscope",
    image: "/images/services/family-medicine.webp",
    category: "especial",
    keywords: ["medicina familiar Houston", "doctor familia Houston", "médico general Houston", "medicina familiar cerca de mi", "doctor español Houston"],
    keywordsEn: ["family medicine Houston", "family doctor Houston TX", "general practitioner Houston", "family doctor near me Houston", "Spanish speaking doctor Houston"],
    features: [
      "Atención para todas las edades",
      "100% en español",
      "Sin cita previa",
      "Aceptamos pacientes sin seguro",
      "Historial médico completo",
      "Vacunas y prevención"
    ],
    featuresEn: ["Care for all ages", "100% Spanish-speaking staff", "No appointment needed", "Uninsured patients welcome", "Complete medical history", "Vaccines & preventive care"],
    highlighted: true,
    order: 1,
  },
  {
    id: "examenes-inmigracion",
    slug: "examenes-inmigracion",
    title: "Examen Médico de Inmigración I-693 Houston",
    shortTitle: "Inmigración",
    description: "Examen I-693 para Green Card en Houston con Civil Surgeons certificados por USCIS. Formulario completo el mismo día, atención en español.",
    longDescription: "¿Necesita el examen médico de inmigración I-693 para su Green Card en Houston? En Clínica Hispana La Caridad contamos con Civil Surgeons certificados por USCIS que completan el formulario oficial con precisión y rapidez. Somos expertos en exámenes de inmigración en Houston TX y entendemos la importancia de acertar desde la primera vez.\n\n**¿Qué incluye el examen médico I-693?**\n\nEl examen de inmigración es un requisito obligatorio para obtener la residencia permanente (Green Card) en Estados Unidos. Durante su visita, nuestro Civil Surgeon realizará:\n\n- Examen físico completo\n- Revisión de historial médico y vacunas\n- Prueba de tuberculosis (TB test)\n- Análisis de sangre requeridos por USCIS\n- Aplicación de vacunas faltantes según el calendario de inmunización de CDC\n- Llenado completo y firma del formulario I-693\n\n**¿Qué documentos necesita traer?**\n\n- Identificación válida con foto (pasaporte, ID estatal o licencia)\n- Récord de vacunas previas (si los tiene disponibles)\n- Formulario I-693 en blanco (nosotros también podemos proporcionarlo)\n\n**¿Cuánto tiempo toma el proceso?**\n\nEn la mayoría de los casos, completamos todo el examen y el formulario I-693 en una sola visita. Los resultados de laboratorio y el formulario firmado están listos el mismo día, para que usted pueda enviarlo a USCIS sin demoras.\n\n**¿Por qué elegir Clínica Hispana La Caridad para su examen I-693?**\n\nNuestros Civil Surgeons tienen amplia experiencia con el proceso de inmigración y completan el formulario correctamente la primera vez, evitando rechazos o retrasos en su caso. Atención 100% en español, vacunas requeridas disponibles en la clínica, y precios competitivos. Ubicados en 5705 Fondren Rd STE 101, Houston TX 77036, con horario extendido de lunes a domingo.",
    titleEn: "I-693 Immigration Medical Exam Houston",
    descriptionEn: "USCIS-certified Civil Surgeons in Houston TX for Green Card immigration medical exams. Complete I-693 form same day, full service in English and Spanish.",
    longDescriptionEn: "Need an I-693 immigration medical exam for your Green Card in Houston? At Clínica Hispana La Caridad, our USCIS-certified Civil Surgeons complete the official I-693 form accurately and efficiently. We specialize in immigration physicals in Houston TX and understand how important it is to get everything right the first time.\n\n**What does the I-693 immigration medical exam include?**\n\nThe immigration physical is a mandatory requirement to obtain permanent residency (Green Card) in the United States. During your visit, our Civil Surgeon will perform:\n\n- Complete physical examination\n- Medical history and vaccination record review\n- Tuberculosis (TB) test\n- Required blood tests per USCIS guidelines\n- Administration of any missing vaccines per CDC immunization schedule\n- Complete completion and signing of Form I-693\n\n**What documents should you bring?**\n\n- Valid government-issued photo ID (passport, state ID, or driver's license)\n- Previous vaccination records (if available)\n- Blank Form I-693 (we can also provide one for you)\n\n**How long does the process take?**\n\nIn most cases, we complete the full exam and Form I-693 in a single visit. Lab results and the signed form are ready the same day, so you can submit your application to USCIS without delay.\n\n**Why choose Clínica Hispana La Caridad for your I-693 exam?**\n\nOur Civil Surgeons have extensive experience with the immigration process and complete the form correctly the first time — avoiding rejections or delays in your case. Full Spanish-language service available, required vaccines on-site, and competitive pricing. Located at 5705 Fondren Rd STE 101, Houston TX 77036, with extended hours Monday through Saturday.",
    icon: "FileText",
    image: "/images/services/immigration.webp",
    category: "especial",
    keywords: ["examen médico inmigración Houston", "I-693 Houston", "civil surgeon Houston", "médico inmigración", "examen green card Houston"],
    keywordsEn: ["immigration medical exam Houston", "I-693 Houston TX", "civil surgeon Houston", "immigration doctor Houston", "Green Card medical exam Houston"],
    features: [
      "Civil Surgeons certificados USCIS",
      "Formulario I-693 completo",
      "Vacunas requeridas disponibles",
      "Resultados el mismo día",
      "Atención 100% en español",
      "Precios competitivos"
    ],
    featuresEn: ["USCIS-certified Civil Surgeons", "Complete I-693 form", "Required vaccines available", "Same-day results", "Full Spanish-language service", "Competitive pricing"],
    highlighted: true,
    order: 2,
  },
  {
    id: "enfermedades-transmision-sexual",
    slug: "enfermedades-transmision-sexual",
    title: "Pruebas STD Confidenciales Houston",
    shortTitle: "STD",
    description: "Pruebas de enfermedades de transmisión sexual en Houston TX. VIH, herpes, clamidia, gonorrea y sífilis. Resultados rápidos y confidenciales.",
    longDescription: "Ofrecemos pruebas confidenciales de enfermedades de transmisión sexual (ETS/STD) en Houston TX. Nuestro laboratorio proporciona resultados rápidos con tratamiento disponible inmediatamente y consejería profesional en un ambiente discreto, privado y sin juicio.\n\n**Pruebas disponibles:**\n\n- VIH (HIV)\n- Herpes (HSV-1 y HSV-2)\n- Clamidia\n- Gonorrea\n- Sífilis (RPR/VDRL)\n- Hepatitis B y C\n- Tricomoniasis\n- VPH (Virus del Papiloma Humano)\n\n**¿Cómo funciona el proceso?**\n\nPuede visitarnos sin cita previa. La consulta es completamente privada y confidencial. Nuestro médico evaluará sus síntomas, ordenará las pruebas necesarias (análisis de sangre, orina, o hisopado según el caso), y recibirá sus resultados de forma segura. Si el resultado es positivo, el tratamiento antibiótico o antiviral se prescribe el mismo día.\n\n**¿Por qué es importante hacerse pruebas?**\n\nMuchas enfermedades de transmisión sexual no presentan síntomas visibles pero pueden causar complicaciones serias si no se tratan a tiempo, incluyendo infertilidad, daño a órganos, y transmisión a la pareja. Las pruebas regulares son la mejor forma de proteger su salud y la de su familia.\n\n**Ambiente seguro y sin juicio**\n\nEntendemos que este tema puede ser difícil de hablar. En Clínica Hispana La Caridad, nuestro equipo médico en Houston le atiende con respeto, profesionalismo y total confidencialidad. Atención 100% en español con precios accesibles para la comunidad hispana.",
    titleEn: "Confidential STD Testing Houston TX",
    descriptionEn: "STD testing in Houston TX — HIV, herpes, chlamydia, gonorrhea, and syphilis. Fast, confidential results with same-day treatment available.",
    longDescriptionEn: "We offer confidential sexually transmitted disease (STD/STI) testing in Houston TX. Our on-site lab provides fast results with immediate treatment available and professional counseling — all in a discreet, private, and judgment-free environment.\n\n**Available STD tests:**\n\n- HIV\n- Herpes (HSV-1 and HSV-2)\n- Chlamydia\n- Gonorrhea\n- Syphilis (RPR/VDRL)\n- Hepatitis B and C\n- Trichomoniasis\n- HPV (Human Papillomavirus)\n\n**How does the process work?**\n\nNo appointment is necessary. Your visit is completely private and confidential. Our physician will review your symptoms, order the appropriate tests (blood draw, urine sample, or swab depending on your situation), and deliver your results securely. If a result comes back positive, antibiotic or antiviral treatment is prescribed the same day.\n\n**Why is STD testing important?**\n\nMany sexually transmitted infections have no visible symptoms but can lead to serious complications if left untreated — including infertility, organ damage, and transmission to partners. Regular testing is the best way to protect your health and the health of those around you.\n\n**A safe, judgment-free environment**\n\nWe understand that this topic can be difficult to discuss. At Clínica Hispana La Caridad, our medical team treats every patient with respect, professionalism, and complete confidentiality. Full Spanish-language service available with affordable pricing for Houston's Hispanic community.",
    icon: "Shield",
    image: "/images/services/std.webp",
    category: "especial",
    keywords: ["prueba STD Houston", "enfermedades transmisión sexual Houston", "prueba VIH Houston", "test ETS Houston confidencial"],
    keywordsEn: ["STD testing Houston", "STI testing Houston TX", "HIV test Houston", "confidential STD test Houston", "sexual health clinic Houston"],
    features: [
      "Pruebas 100% confidenciales",
      "Resultados rápidos",
      "Tratamiento inmediato disponible",
      "Consejería profesional",
      "Ambiente discreto y privado",
      "Sin juicio"
    ],
    featuresEn: ["100% confidential testing", "Fast results", "Same-day treatment available", "Professional counseling", "Discreet, private environment", "Judgment-free care"],
    highlighted: false,
    order: 3,
  },
  {
    id: "urologia",
    slug: "urologia",
    title: "Urología en Houston TX",
    shortTitle: "Urología",
    description: "Servicios de urología en Houston para hombres y mujeres. Diagnóstico y tratamiento de próstata, infecciones urinarias e incontinencia.",
    longDescription: "Ofrecemos servicios de urología en Houston TX para hombres y mujeres, incluyendo diagnóstico y tratamiento de condiciones del sistema urinario y reproductivo masculino. Nuestro equipo médico en Houston brinda atención personalizada en español con tecnología moderna para diagnósticos precisos.\n\n**Condiciones que evaluamos y tratamos:**\n\n- Infecciones urinarias recurrentes\n- Problemas de próstata (agrandamiento, PSA elevado)\n- Incontinencia urinaria\n- Dolor al orinar o sangre en la orina\n- Cálculos renales\n- Disfunción eréctil\n- Infecciones del tracto urinario en hombres\n- Evaluación de vejiga\n\n**¿Qué incluye la consulta de urología?**\n\nDurante su visita, nuestro médico realizará una evaluación completa de sus síntomas, examen físico, y ordenará los estudios necesarios como análisis de orina, análisis de sangre (incluyendo PSA para hombres), o ultrasonido si es necesario. Todo disponible en nuestra clínica en Houston.\n\n**¿Cuándo debe consultar por urología?**\n\nSi experimenta dolor al orinar, necesidad frecuente de ir al baño, dificultad para vaciar la vejiga, sangre en la orina, o dolor en la zona pélvica o lumbar, es importante consultar a un profesional. La detección temprana puede prevenir complicaciones mayores.\n\n**Atención especializada en Houston**\n\nSi su condición requiere atención especializada adicional, nuestro equipo médico le referirá a urólogos certificados de confianza en el área de Houston. Atención en español, sin cita previa, con precios accesibles.",
    titleEn: "Urology Services Houston TX",
    descriptionEn: "Urology care in Houston for men and women. Diagnosis and treatment of prostate conditions, urinary tract infections, and incontinence.",
    longDescriptionEn: "We provide urology services in Houston TX for both men and women, including diagnosis and treatment of urinary tract and male reproductive system conditions. Our Houston medical team delivers personalized, Spanish-language care using modern diagnostic technology for accurate results.\n\n**Conditions we evaluate and treat:**\n\n- Recurrent urinary tract infections (UTIs)\n- Prostate issues (enlarged prostate, elevated PSA)\n- Urinary incontinence\n- Pain or burning during urination, or blood in urine\n- Kidney stones\n- Erectile dysfunction\n- Male urinary tract infections\n- Bladder evaluation\n\n**What does a urology consultation include?**\n\nDuring your visit, our physician will conduct a complete evaluation of your symptoms, perform a physical exam, and order any necessary tests — including urinalysis, blood work (PSA screening for men), or an ultrasound if indicated. All diagnostic services are available in our Houston clinic.\n\n**When should you see a doctor for urology concerns?**\n\nIf you experience painful urination, frequent urges to urinate, difficulty emptying your bladder, blood in your urine, or pelvic and lower back pain, it's important to seek professional evaluation. Early detection can prevent more serious complications.\n\n**Specialized care in Houston**\n\nIf your condition requires additional specialist care, our medical team will refer you to trusted, board-certified urologists in the Houston area. Spanish-language service available, walk-ins welcome, with affordable pricing.",
    icon: "Activity",
    image: "/images/services/urology.webp",
    category: "especialidad",
    keywords: ["urología Houston", "urólogo Houston", "problemas próstata Houston", "urólogo español Houston"],
    keywordsEn: ["urology Houston TX", "urologist Houston", "prostate problems Houston", "Spanish speaking urologist Houston", "urinary tract specialist Houston"],
    features: [
      "Diagnóstico completo",
      "Tratamiento de infecciones",
      "Evaluación de próstata",
      "Incontinencia urinaria",
      "Atención hombres y mujeres",
      "Referencia a especialistas"
    ],
    featuresEn: ["Comprehensive diagnosis", "Infection treatment", "Prostate evaluation", "Urinary incontinence care", "Men & women welcome", "Specialist referrals available"],
    highlighted: false,
    order: 4,
  },
  {
    id: "condiciones-cronicas",
    slug: "condiciones-cronicas",
    title: "Control de Diabetes e Hipertensión Houston",
    shortTitle: "Crónicas",
    description: "Manejo de diabetes, hipertensión y colesterol en Houston TX. Monitoreo continuo, ajuste de medicamentos y educación en español.",
    longDescription: "Programa integral para el manejo de condiciones crónicas en Houston TX. La diabetes, hipertensión arterial y colesterol alto son condiciones que afectan a millones de hispanos en Estados Unidos. En Clínica Hispana La Caridad ofrecemos un programa de seguimiento continuo para ayudarle a controlar su salud.\n\n**¿Qué incluye nuestro programa de control de condiciones crónicas?**\n\n- Monitoreo regular de glucosa en sangre y hemoglobina A1C\n- Medición y control de presión arterial\n- Panel de colesterol y lípidos\n- Evaluación de función renal y hepática\n- Ajuste de medicamentos según sus niveles\n- Educación personalizada sobre dieta y estilo de vida\n- Plan de seguimiento con visitas programadas\n\n**Diabetes: por qué el control es importante**\n\nLa diabetes no controlada puede causar daño a los riñones, pérdida de visión, problemas de circulación y neuropatía. Con monitoreo regular y ajuste de medicamentos, la mayoría de los pacientes logran mantener sus niveles de glucosa en rango saludable y prevenir complicaciones.\n\n**Hipertensión: el enemigo silencioso**\n\nLa presión arterial alta generalmente no presenta síntomas pero aumenta el riesgo de ataque cardíaco y derrame cerebral. Nuestro equipo médico en Houston monitorea su presión en cada visita y ajusta su tratamiento para mantenerla bajo control.\n\n**¿Por qué elegir Clínica Hispana La Caridad?**\n\nNuestro equipo médico habla español, entiende los factores culturales y alimenticios de la comunidad hispana, y ofrece educación en un idioma que usted comprende completamente. Laboratorio en la clínica con resultados el mismo día, precios accesibles, y horario extendido para que no tenga que faltar al trabajo.",
    titleEn: "Diabetes & Hypertension Management Houston",
    descriptionEn: "Diabetes, hypertension, and cholesterol management in Houston TX. Ongoing monitoring, medication adjustments, and patient education in English and Spanish.",
    longDescriptionEn: "We offer a comprehensive chronic condition management program in Houston TX. Diabetes, high blood pressure, and high cholesterol affect millions of Hispanic Americans — and at Clínica Hispana La Caridad, we provide a structured, ongoing monitoring program to help you take control of your health.\n\n**What our chronic condition program includes:**\n\n- Regular blood glucose and hemoglobin A1C monitoring\n- Blood pressure measurement and control\n- Cholesterol and lipid panel testing\n- Kidney and liver function evaluation\n- Medication adjustments based on your current levels\n- Personalized education on diet and lifestyle changes\n- Scheduled follow-up visits and care plan\n\n**Diabetes: why consistent management matters**\n\nUncontrolled diabetes can cause kidney damage, vision loss, poor circulation, and neuropathy. With regular monitoring and timely medication adjustments, most patients are able to keep their blood sugar levels in a healthy range and avoid serious complications.\n\n**Hypertension: the silent threat**\n\nHigh blood pressure typically presents no symptoms, yet it significantly increases the risk of heart attack and stroke. Our Houston medical team checks your blood pressure at every visit and fine-tunes your treatment to keep it under control.\n\n**Why choose Clínica Hispana La Caridad?**\n\nOur medical team is fluent in Spanish and understands the cultural and dietary factors unique to the Hispanic community. We offer education you can truly understand, on-site lab services with same-day results, affordable pricing, and extended hours so you never have to miss work for an appointment.",
    icon: "Heart",
    image: "/images/services/chronic-conditions.jpg",
    category: "especialidad",
    keywords: ["control diabetes Houston", "hipertensión Houston", "condiciones crónicas Houston", "médico diabetes español Houston"],
    keywordsEn: ["diabetes management Houston", "hypertension doctor Houston TX", "chronic conditions clinic Houston", "Spanish speaking diabetes doctor Houston", "high blood pressure treatment Houston"],
    features: [
      "Monitoreo de glucosa",
      "Control de presión arterial",
      "Manejo de colesterol",
      "Ajuste de medicamentos",
      "Educación en español",
      "Seguimiento continuo"
    ],
    featuresEn: ["Blood glucose monitoring", "Blood pressure control", "Cholesterol management", "Medication adjustments", "Patient education in Spanish", "Ongoing follow-up care"],
    highlighted: true,
    order: 5,
  },
  {
    id: "laboratorio",
    slug: "laboratorio",
    title: "Laboratorio Clínico Houston - Resultados el Mismo Día",
    shortTitle: "Laboratorio",
    description: "Análisis de sangre y laboratorio clínico en Houston TX. Glucosa, colesterol, hemograma, tiroides y más. Resultados el mismo día.",
    longDescription: "Nuestro laboratorio clínico en Houston TX cuenta con tecnología moderna para análisis rápidos y precisos. Ofrecemos una amplia gama de pruebas de laboratorio con resultados el mismo día, para que usted y su médico puedan tomar decisiones informadas sin esperar días.\n\n**Pruebas de laboratorio disponibles:**\n\n- Hemograma completo (CBC)\n- Glucosa en ayunas y hemoglobina A1C\n- Panel de colesterol y lípidos\n- Panel metabólico completo (CMP)\n- Función tiroidea (TSH, T3, T4)\n- Función hepática y renal\n- Análisis de orina completo\n- Prueba de embarazo\n- Ácido úrico\n- Vitamina D y B12\n- Panel de hierro y ferritina\n- Pruebas de ETS (VIH, hepatitis, sífilis)\n\n**¿Cómo funciona el proceso?**\n\nPuede visitarnos sin cita previa. Nuestro personal capacitado realiza la toma de muestra de sangre de forma rápida y profesional. Para pruebas de glucosa y colesterol, se recomienda ayuno de 8-12 horas. Los resultados están disponibles el mismo día en la mayoría de los casos.\n\n**¿Para qué sirven los análisis de sangre?**\n\nLos exámenes de laboratorio son fundamentales para detectar condiciones de salud antes de que presenten síntomas, monitorear enfermedades crónicas como diabetes e hipertensión, y evaluar el funcionamiento general de sus órganos.\n\n**Laboratorio en la clínica**\n\nA diferencia de otros laboratorios en Houston que requieren cita y tardan días en entregar resultados, nuestro laboratorio está dentro de la clínica. Esto significa que su médico puede ordenar y revisar sus resultados en la misma visita, ahorrándole tiempo y visitas adicionales. Atención en español con precios accesibles.",
    titleEn: "Clinical Laboratory Houston - Same-Day Results",
    descriptionEn: "Blood tests and clinical lab services in Houston TX. Glucose, cholesterol, CBC, thyroid panels, and more — results available the same day.",
    longDescriptionEn: "Our clinical laboratory in Houston TX features modern technology for fast, accurate analysis. We offer a wide range of lab tests with same-day results so you and your doctor can make informed decisions without waiting days.\n\n**Available lab tests:**\n\n- Complete blood count (CBC)\n- Fasting glucose and hemoglobin A1C\n- Cholesterol and lipid panel\n- Comprehensive metabolic panel (CMP)\n- Thyroid function (TSH, T3, T4)\n- Liver and kidney function\n- Complete urinalysis\n- Pregnancy test\n- Uric acid\n- Vitamin D and B12\n- Iron and ferritin panel\n- STD testing (HIV, hepatitis, syphilis)\n\n**How does it work?**\n\nNo appointment needed. Our trained staff performs blood draws quickly and professionally. For glucose and cholesterol tests, an 8–12 hour fast is recommended. Results are available the same day in most cases.\n\n**Why do blood tests matter?**\n\nLab tests are essential for detecting health conditions before symptoms appear, monitoring chronic diseases like diabetes and hypertension, and evaluating the overall function of your vital organs.\n\n**On-site lab — no referral needed**\n\nUnlike standalone labs in Houston that require appointments and take days to return results, our laboratory is located inside the clinic. This means your doctor can order and review your results during the same visit — saving you time and extra trips. Spanish-language service available with affordable, transparent pricing.",
    icon: "Flask",
    image: "/images/services/laboratory.webp",
    category: "diagnostico",
    keywords: ["laboratorio clínico Houston", "análisis sangre Houston", "exámenes médicos Houston", "prueba glucosa Houston"],
    keywordsEn: ["clinical laboratory Houston", "blood test Houston TX", "same-day lab results Houston", "glucose test Houston", "medical lab near me Houston"],
    features: [
      "Resultados el mismo día",
      "Análisis de sangre completos",
      "Glucosa y colesterol",
      "Panel metabólico",
      "Exámenes de tiroides",
      "Sin largas esperas"
    ],
    featuresEn: ["Same-day results", "Comprehensive blood panels", "Glucose & cholesterol testing", "Metabolic panel", "Thyroid testing", "No long waits"],
    highlighted: true,
    order: 6,
  },
  {
    id: "ultrasonido",
    slug: "ultrasonido",
    title: "Ultrasonido y Ecografía Houston TX",
    shortTitle: "Ultrasonido",
    description: "Estudios de ultrasonido en Houston: abdominal, pélvico, tiroides y más. Tecnología avanzada con resultados interpretados por profesionales.",
    longDescription: "Realizamos estudios de ultrasonido y ecografía en Houston TX para diagnóstico de diversas condiciones médicas. Nuestra clínica cuenta con equipo de imagen avanzado y resultados interpretados por profesionales médicos.\n\n**Tipos de ultrasonido disponibles:**\n\n- Ultrasonido abdominal (hígado, vesícula, páncreas, riñones)\n- Ultrasonido pélvico (útero, ovarios, vejiga)\n- Ultrasonido de tiroides\n- Ultrasonido de tejidos blandos\n- Ultrasonido renal\n- Ecografía obstétrica básica\n\n**¿Cuándo se necesita un ultrasonido?**\n\nSu médico puede ordenar un ultrasonido cuando sospecha de cálculos en la vesícula o riñón, quistes, masas o inflamación en órganos internos, problemas de tiroides, dolor abdominal o pélvico inexplicable, o como parte de un chequeo de rutina.\n\n**¿Cómo funciona el estudio?**\n\nEl ultrasonido es un procedimiento no invasivo, sin dolor y sin radiación. Se utiliza una sonda que emite ondas de sonido para crear imágenes de los órganos internos. Dependiendo del tipo de estudio, puede requerir ayuno previo o vejiga llena. Nuestro personal le indicará las instrucciones de preparación al momento de agendar.\n\n**Resultados el mismo día**\n\nLas imágenes son interpretadas por profesionales y los resultados se entregan el mismo día. Si se detecta alguna anomalía, nuestro médico le explicará los hallazgos en español y le indicará los pasos a seguir, incluyendo referencia a especialistas si es necesario. Precios accesibles para la comunidad hispana de Houston.",
    titleEn: "Ultrasound & Sonogram Services Houston TX",
    descriptionEn: "Diagnostic ultrasound in Houston: abdominal, pelvic, thyroid, and more. Advanced imaging technology with professional interpretation and fast results.",
    longDescriptionEn: "We perform diagnostic ultrasound and sonography studies in Houston TX for a wide range of medical conditions. Our clinic is equipped with advanced imaging technology and results are interpreted by qualified medical professionals.\n\n**Types of ultrasound available:**\n\n- Abdominal ultrasound (liver, gallbladder, pancreas, kidneys)\n- Pelvic ultrasound (uterus, ovaries, bladder)\n- Thyroid ultrasound\n- Soft tissue ultrasound\n- Renal ultrasound\n- Basic obstetric ultrasound\n\n**When is an ultrasound needed?**\n\nYour doctor may order an ultrasound when there is suspicion of gallstones or kidney stones, cysts, masses, or organ inflammation, thyroid nodules, unexplained abdominal or pelvic pain, or as part of a routine health checkup.\n\n**What to expect during the procedure**\n\nAn ultrasound is completely non-invasive, painless, and does not use radiation. A handheld probe is used to send sound waves that create images of your internal organs. Depending on the type of study, you may need to fast beforehand or arrive with a full bladder. Our staff will provide preparation instructions when you schedule.\n\n**Same-day results with professional interpretation**\n\nImages are reviewed by medical professionals and results are delivered the same day. If an abnormality is found, our physician will explain the findings in plain language and outline the next steps — including specialist referrals if needed. Affordable pricing for Houston's Hispanic community.",
    icon: "Monitor",
    image: "/images/services/ultrasound.webp",
    category: "diagnostico",
    keywords: ["ultrasonido Houston", "ecografía Houston", "sonograma Houston", "ultrasonido abdominal Houston"],
    keywordsEn: ["ultrasound Houston TX", "sonogram Houston", "pelvic ultrasound Houston", "abdominal ultrasound Houston", "diagnostic imaging Houston"],
    features: [
      "Ultrasonido abdominal",
      "Ultrasonido pélvico",
      "Ultrasonido de tiroides",
      "Resultados rápidos",
      "Tecnología avanzada",
      "Interpretación profesional"
    ],
    featuresEn: ["Abdominal ultrasound", "Pelvic ultrasound", "Thyroid ultrasound", "Fast results", "Advanced imaging technology", "Professional interpretation"],
    highlighted: false,
    order: 7,
  },
  {
    id: "ginecologia",
    slug: "ginecologia",
    title: "Ginecología en Houston - Salud de la Mujer",
    shortTitle: "Ginecología",
    description: "Servicios de ginecología en Houston TX en español. Papanicolaou, examen pélvico, examen de seno y atención prenatal. Sin cita previa.",
    longDescription: "Brindamos atención integral de ginecología en Houston TX para la salud de la mujer en todas las etapas de su vida. Nuestro equipo médico entiende sus necesidades y ofrece atención confidencial 100% en español.\n\n**Servicios de ginecología que ofrecemos:**\n\n- Examen de Papanicolaou (Pap smear)\n- Examen clínico de seno\n- Examen pélvico completo\n- Diagnóstico y tratamiento de infecciones vaginales\n- Evaluación de irregularidades menstruales\n- Consulta de menopausia y manejo de síntomas\n- Atención prenatal básica\n- Pruebas de embarazo y orientación\n- Detección de VPH\n\n**¿Cada cuánto debe hacerse el Papanicolaou?**\n\nLas guías médicas recomiendan que las mujeres entre 21 y 65 años se realicen el Papanicolaou cada 3 años, o cada 5 años si se combina con la prueba de VPH. Sin embargo, su médico puede recomendar una frecuencia diferente según su historial. Este examen es fundamental para la detección temprana del cáncer cervical.\n\n**Salud de la mujer en cada etapa**\n\nYa sea que esté buscando anticoncepción, planificando un embarazo, experimentando síntomas de menopausia, o simplemente necesite su chequeo anual, nuestro equipo en Houston le brinda la atención que necesita en un ambiente cómodo y de confianza.\n\n**Atención confidencial y respetuosa**\n\nEntendemos que los temas de salud femenina pueden ser sensibles. En Clínica Hispana La Caridad, cada consulta es privada y confidencial. Atendemos sin cita previa, aceptamos pacientes con o sin seguro, y ofrecemos precios accesibles para la comunidad hispana de Houston.",
    titleEn: "Gynecology in Houston - Women's Health Care",
    descriptionEn: "Women's gynecology services in Houston TX. Pap smears, pelvic exams, breast exams, and basic prenatal care — no appointment needed, Spanish-speaking staff.",
    longDescriptionEn: "We provide comprehensive gynecology care in Houston TX to support women's health at every stage of life. Our medical team understands your needs and offers confidential, compassionate care with full Spanish-language service.\n\n**Gynecology services we offer:**\n\n- Pap smear (cervical cancer screening)\n- Clinical breast exam\n- Complete pelvic exam\n- Diagnosis and treatment of vaginal infections\n- Evaluation of irregular periods and menstrual concerns\n- Menopause consultation and symptom management\n- Basic prenatal care\n- Pregnancy testing and counseling\n- HPV detection\n\n**How often should you get a Pap smear?**\n\nMedical guidelines recommend that women between 21 and 65 get a Pap smear every 3 years, or every 5 years when combined with an HPV test. Your doctor may recommend a different frequency based on your personal history. This screening is essential for the early detection of cervical cancer.\n\n**Women's health at every stage**\n\nWhether you're seeking birth control, planning a pregnancy, managing menopause symptoms, or simply due for your annual checkup, our Houston team provides the care you need in a comfortable, trustworthy environment.\n\n**Confidential and respectful care**\n\nWe understand that women's health topics can feel sensitive. At Clínica Hispana La Caridad, every visit is private and confidential. We welcome walk-ins, accept patients with or without insurance, and offer affordable pricing for Houston's Hispanic community.",
    icon: "GenderFemale",
    image: "/images/services/gynecology.webp",
    category: "mujer",
    keywords: ["ginecología Houston", "Papanicolaou Houston", "salud mujer Houston", "ginecólogo español Houston"],
    keywordsEn: ["gynecology Houston TX", "Pap smear Houston", "women's health clinic Houston", "Spanish speaking gynecologist Houston", "OB GYN Houston"],
    features: [
      "Examen de Papanicolaou",
      "Examen de seno",
      "Examen pélvico completo",
      "Tratamiento de infecciones",
      "Atención prenatal básica",
      "Consulta de menopausia"
    ],
    featuresEn: ["Pap smear screening", "Breast exam", "Complete pelvic exam", "Infection treatment", "Basic prenatal care", "Menopause consultation"],
    highlighted: true,
    order: 8,
  },
  {
    id: "planificacion-familiar",
    slug: "planificacion-familiar",
    title: "Planificación Familiar Houston TX",
    shortTitle: "Planificación",
    description: "Métodos anticonceptivos en Houston: píldoras, inyecciones, implantes y DIU. Consejería profesional en español para parejas.",
    longDescription: "Ofrecemos servicios de planificación familiar en Houston TX con consejería completa y personalizada sobre los métodos anticonceptivos disponibles. Nuestro equipo médico ayuda a las mujeres y parejas a tomar decisiones informadas sobre su salud reproductiva.\n\n**Métodos anticonceptivos disponibles:**\n\n- Píldoras anticonceptivas (varias opciones)\n- Inyecciones anticonceptivas (Depo-Provera)\n- Implantes subdérmicos (Nexplanon)\n- Dispositivo intrauterino (DIU)\n- Parches anticonceptivos\n- Anillo vaginal\n- Métodos de barrera\n\n**¿Cómo elegir el método correcto?**\n\nDurante la consulta de planificación familiar, nuestro médico evaluará su historial médico, edad, estilo de vida, planes futuros de embarazo, y cualquier condición de salud existente. Con esta información, le recomendará las opciones más adecuadas para usted y le explicará los beneficios y posibles efectos secundarios de cada método.\n\n**Seguimiento continuo**\n\nLa planificación familiar no termina con la elección de un método. Ofrecemos visitas de seguimiento para asegurarnos de que su método funcione bien, ajustar si es necesario, y responder cualquier pregunta. Si desea cambiar de método o planificar un embarazo, le acompañamos en la transición.\n\n**Atención confidencial en Houston**\n\nTodas las consultas de planificación familiar son privadas y confidenciales. Atendemos en español, sin cita previa, y con precios accesibles. Ubicados en 5705 Fondren Rd STE 101, Houston TX 77036.",
    titleEn: "Family Planning Houston TX",
    descriptionEn: "Contraception options in Houston: birth control pills, injections, implants, and IUDs. Professional counseling in English and Spanish for individuals and couples.",
    longDescriptionEn: "We offer family planning services in Houston TX with comprehensive, personalized counseling on all available contraceptive methods. Our medical team helps women and couples make well-informed decisions about their reproductive health.\n\n**Available contraceptive methods:**\n\n- Birth control pills (multiple formulations available)\n- Contraceptive injections (Depo-Provera)\n- Subdermal implants (Nexplanon)\n- Intrauterine device (IUD)\n- Contraceptive patch\n- Vaginal ring\n- Barrier methods\n\n**How do we help you choose the right method?**\n\nDuring your family planning consultation, our physician will review your medical history, age, lifestyle, future pregnancy plans, and any existing health conditions. Using this information, we'll recommend the most suitable options and clearly explain the benefits and possible side effects of each method.\n\n**Ongoing follow-up care**\n\nFamily planning doesn't end when you choose a method. We offer follow-up visits to make sure your chosen method is working well, make adjustments if needed, and answer any questions. If you decide to change methods or are ready to plan a pregnancy, we'll guide you through every step of the transition.\n\n**Confidential care in Houston**\n\nAll family planning consultations are completely private and confidential. Spanish-language service available, walk-ins welcome, with affordable pricing. Located at 5705 Fondren Rd STE 101, Houston TX 77036.",
    icon: "Users",
    image: "/images/services/family-planning.webp",
    category: "mujer",
    keywords: ["planificación familiar Houston", "anticonceptivos Houston", "métodos anticonceptivos Houston", "DIU Houston"],
    keywordsEn: ["family planning Houston TX", "birth control Houston", "contraception clinic Houston", "IUD Houston TX", "contraceptive options Houston"],
    features: [
      "Consejería personalizada",
      "Píldoras anticonceptivas",
      "Inyecciones anticonceptivas",
      "Implantes subdérmicos",
      "DIU disponible",
      "Seguimiento continuo"
    ],
    featuresEn: ["Personalized counseling", "Birth control pills", "Contraceptive injections", "Subdermal implants", "IUD available", "Ongoing follow-up care"],
    highlighted: false,
    order: 9,
  },
  {
    id: "vacunas-anticonceptivas",
    slug: "vacunas-anticonceptivas",
    title: "Inyección Anticonceptiva Houston",
    shortTitle: "Anticonceptivas",
    description: "Inyecciones anticonceptivas Depo-Provera en Houston TX. Aplicación profesional con seguimiento médico. Sin cita previa.",
    longDescription: "Aplicamos inyecciones anticonceptivas Depo-Provera en Houston TX con seguimiento médico profesional. Esta es una opción conveniente y altamente efectiva para mujeres que prefieren un método anticonceptivo que no requiere tomar una píldora diaria.\n\n**¿Qué es la inyección Depo-Provera?**\n\nLa inyección anticonceptiva Depo-Provera contiene la hormona progestina y se aplica cada 3 meses (12 semanas). Tiene una efectividad superior al 99% cuando se aplica a tiempo y es una de las opciones más prácticas de anticoncepción disponibles.\n\n**Ventajas de la inyección anticonceptiva:**\n\n- Solo necesita aplicarse cada 3 meses\n- No requiere recordar tomar una píldora diaria\n- Alta efectividad anticonceptiva\n- Puede reducir cólicos menstruales\n- Discreta — nadie necesita saber que la usa\n- Reversible — la fertilidad regresa después de suspenderla\n\n**¿Cómo es el proceso?**\n\nEn su primera visita, nuestro médico evaluará su historial médico para asegurarse de que este método sea seguro para usted. La inyección se aplica en el brazo o glúteo y toma solo unos minutos. Le programaremos un recordatorio para su próxima aplicación en 12 semanas.\n\n**Seguimiento médico incluido**\n\nCon cada aplicación, nuestro equipo verifica que no haya efectos secundarios y responde sus preguntas. Si en algún momento desea cambiar de método, le orientamos sobre las alternativas disponibles. Atención en español, sin cita previa, con precios accesibles en Houston TX.",
    titleEn: "Birth Control Shot Houston TX",
    descriptionEn: "Depo-Provera contraceptive injections in Houston TX. Professional administration with medical follow-up. No appointment needed.",
    longDescriptionEn: "We provide professional Depo-Provera contraceptive injections in Houston TX with medical follow-up. This is a convenient and highly effective option for women who prefer a birth control method that doesn't require taking a daily pill.\n\n**What is the Depo-Provera shot?**\n\nThe Depo-Provera injection contains the hormone progestin and is administered every 3 months (12 weeks). It has over 99% effectiveness when administered on time and is one of the most practical contraceptive options available.\n\n**Benefits of the birth control shot:**\n\n- Only needs to be administered every 3 months\n- No daily pill to remember\n- Highly effective contraception\n- Can reduce menstrual cramps\n- Discreet — no one needs to know you use it\n- Reversible — fertility returns after stopping\n\n**How does the process work?**\n\nDuring your first visit, our physician will review your medical history to ensure this method is safe for you. The injection is administered in the arm or buttock and takes just a few minutes. We'll schedule a reminder for your next injection in 12 weeks.\n\n**Medical follow-up included**\n\nWith each injection, our team checks for side effects and answers your questions. If at any point you wish to switch methods, we'll guide you through the available alternatives. Spanish-language service, walk-ins welcome, affordable pricing in Houston TX.",
    icon: "Syringe",
    image: "/images/services/contraceptive-vaccines.webp",
    category: "mujer",
    keywords: ["inyección anticonceptiva Houston", "Depo-Provera Houston", "anticonceptivo inyectable Houston"],
    keywordsEn: ["birth control shot Houston", "Depo-Provera Houston TX", "contraceptive injection Houston", "birth control clinic Houston", "women's health Houston"],
    features: [
      "Inyección Depo-Provera",
      "Aplicación profesional",
      "Seguimiento médico",
      "Efectividad comprobada",
      "Sin cita previa",
      "Atención en español"
    ],
    featuresEn: ["Depo-Provera injection", "Professional administration", "Medical follow-up", "Proven effectiveness", "No appointment needed", "Spanish & English care"],
    highlighted: false,
    order: 10,
  },
  {
    id: "extraccion-implantes",
    slug: "extraccion-implantes",
    title: "Extracción de Implantes Anticonceptivos Houston",
    shortTitle: "Implantes",
    description: "Retiro seguro de Nexplanon e Implanon en Houston TX. Procedimiento rápido con anestesia local y recuperación inmediata.",
    longDescription: "Realizamos la extracción segura de implantes anticonceptivos subdérmicos (Nexplanon e Implanon) en Houston TX. Este procedimiento es necesario cuando el implante ha cumplido su vida útil (3-5 años), cuando la paciente desea cambiar de método, o cuando planifica un embarazo.\n\n**¿Cuándo debe retirarse el implante?**\n\n- Cuando ha pasado su fecha de vencimiento (3 años para Nexplanon, 3 años para Implanon)\n- Si desea quedar embarazada\n- Si experimenta efectos secundarios que desea resolver\n- Si prefiere cambiar a otro método anticonceptivo\n\n**¿Cómo es el procedimiento de extracción?**\n\nLa extracción del implante es un procedimiento ambulatorio que toma aproximadamente 15-20 minutos. Nuestro médico localiza el implante en su brazo, aplica anestesia local para que no sienta dolor, y realiza una pequeña incisión para retirarlo. Se coloca un vendaje y puede retomar sus actividades normales el mismo día.\n\n**Después de la extracción**\n\nLa fertilidad regresa rápidamente después de retirar el implante. Si desea un nuevo implante o cambiar a otro método anticonceptivo, podemos hacerlo en la misma visita. Nuestro equipo le brindará consejería sobre todas las opciones disponibles.\n\n**Atención profesional en Houston**\n\nNuestro personal está capacitado para realizar este procedimiento de forma segura y cómoda. Atención en español, sin cita previa, con precios accesibles. Ubicados en 5705 Fondren Rd STE 101, Houston TX 77036.",
    titleEn: "Contraceptive Implant Removal Houston TX",
    descriptionEn: "Safe removal of Nexplanon and Implanon implants in Houston TX. Quick procedure with local anesthesia and immediate recovery.",
    longDescriptionEn: "We perform safe removal of contraceptive implants (Nexplanon and Implanon) in Houston TX. This procedure is needed when the implant has reached its expiration (3-5 years), when you wish to switch methods, or when planning a pregnancy.\n\n**When should the implant be removed?**\n\n- When it has passed its expiration date (3 years for Nexplanon/Implanon)\n- If you want to become pregnant\n- If you experience side effects you want to resolve\n- If you prefer to switch to a different contraceptive method\n\n**What to expect during the procedure**\n\nImplant removal is an outpatient procedure that takes approximately 15-20 minutes. Our physician locates the implant in your arm, applies local anesthesia so you feel no pain, and makes a small incision to remove it. A bandage is placed and you can resume normal activities the same day.\n\n**After the removal**\n\nFertility returns quickly after removing the implant. If you want a new implant or to switch to another contraceptive method, we can do it during the same visit. Our team will provide counseling on all available options.\n\n**Professional care in Houston**\n\nOur staff is trained to perform this procedure safely and comfortably. Spanish-language service, walk-ins welcome, affordable pricing. Located at 5705 Fondren Rd STE 101, Houston TX 77036.",
    icon: "Scissors",
    image: "/images/services/implant-removal.webp",
    category: "mujer",
    keywords: ["extracción implante Houston", "quitar Nexplanon Houston", "remover implante anticonceptivo Houston"],
    keywordsEn: ["implant removal Houston", "Nexplanon removal Houston TX", "Implanon removal Houston", "contraceptive implant extraction Houston", "birth control implant removal Houston"],
    features: [
      "Procedimiento seguro",
      "Personal capacitado",
      "Anestesia local incluida",
      "Recuperación rápida",
      "Consejería post-extracción",
      "Opciones alternativas"
    ],
    featuresEn: ["Safe removal procedure", "Trained medical staff", "Local anesthesia included", "Quick recovery", "Post-removal counseling", "Alternative contraceptive options"],
    highlighted: false,
    order: 11,
  },
  {
    id: "electrocardiograma",
    slug: "electrocardiograma",
    title: "Electrocardiograma EKG Houston TX",
    shortTitle: "EKG",
    description: "Electrocardiograma en Houston para detectar arritmias y problemas cardíacos. Resultados inmediatos con interpretación profesional.",
    longDescription: "Realizamos electrocardiogramas (EKG/ECG) en Houston TX para evaluar la actividad eléctrica de su corazón. Este estudio rápido y no invasivo es fundamental para detectar problemas cardíacos a tiempo.\n\n**¿Qué detecta un electrocardiograma?**\n\n- Arritmias (latidos irregulares del corazón)\n- Problemas de conducción eléctrica\n- Señales de ataque cardíaco previo\n- Agrandamiento del corazón\n- Efectos de medicamentos en el corazón\n- Niveles anormales de electrolitos\n\n**¿Cuándo necesita un EKG?**\n\nSu médico puede ordenar un electrocardiograma si experimenta dolor en el pecho, falta de aire, mareos, palpitaciones, o desmayos. También se realiza como parte de exámenes preventivos, antes de cirugías, o para monitorear condiciones cardíacas existentes. Es un requisito común en exámenes físicos para empleo y deportes.\n\n**¿Cómo es el procedimiento?**\n\nEl EKG es completamente indoloro y toma solo 5-10 minutos. Se colocan pequeños electrodos adhesivos en su pecho, brazos y piernas que registran la actividad eléctrica del corazón. No requiere preparación especial y puede retomar sus actividades inmediatamente después.\n\n**Resultados inmediatos**\n\nLos resultados del electrocardiograma están disponibles de inmediato. Nuestro médico interpretará el estudio en español, le explicará los hallazgos, y si se detecta alguna anomalía, le referirá a un cardiólogo de confianza en Houston. Atención sin cita previa con precios accesibles.",
    titleEn: "EKG Electrocardiogram Houston TX",
    descriptionEn: "Electrocardiogram EKG testing in Houston TX to detect arrhythmias and heart conditions. Immediate results with professional interpretation.",
    longDescriptionEn: "We perform electrocardiograms (EKG/ECG) in Houston TX to evaluate your heart's electrical activity. This quick, non-invasive test is essential for detecting heart problems early.\n\n**What does an EKG detect?**\n\n- Arrhythmias (irregular heartbeats)\n- Electrical conduction problems\n- Signs of a previous heart attack\n- Enlarged heart\n- Effects of medications on the heart\n- Abnormal electrolyte levels\n\n**When do you need an EKG?**\n\nYour doctor may order an electrocardiogram if you experience chest pain, shortness of breath, dizziness, palpitations, or fainting. It is also performed as part of preventive exams, before surgeries, or to monitor existing cardiac conditions. It is commonly required for employment and sports physicals.\n\n**How does the procedure work?**\n\nThe EKG is completely painless and takes only 5-10 minutes. Small adhesive electrodes are placed on your chest, arms, and legs to record the heart's electrical activity. No special preparation is needed and you can resume your activities immediately after.\n\n**Immediate results**\n\nEKG results are available right away. Our physician will interpret the study, explain the findings, and if any abnormality is detected, refer you to a trusted cardiologist in Houston. Walk-ins welcome with affordable pricing.",
    icon: "Activity",
    image: "/images/services/ekg.webp",
    category: "diagnostico",
    keywords: ["electrocardiograma Houston", "EKG Houston", "estudio corazón Houston", "ECG Houston TX"],
    keywordsEn: ["EKG Houston TX", "electrocardiogram Houston", "ECG test Houston", "heart test Houston TX", "cardiac evaluation Houston"],
    features: [
      "Resultados inmediatos",
      "Detección de arritmias",
      "Evaluación cardíaca completa",
      "Procedimiento no invasivo",
      "Interpretación profesional",
      "Referencia a cardiólogo"
    ],
    featuresEn: ["Immediate results", "Arrhythmia detection", "Complete cardiac evaluation", "Non-invasive procedure", "Professional interpretation", "Cardiology referral available"],
    highlighted: false,
    order: 12,
  },
  {
    id: "enfermedades-respiratorias",
    slug: "enfermedades-respiratorias",
    title: "Tratamiento Gripe y Enfermedades Respiratorias Houston",
    shortTitle: "Respiratorias",
    description: "Tratamiento de gripe, bronquitis, asma y COVID-19 en Houston TX. Diagnóstico rápido, nebulizaciones y pruebas disponibles.",
    longDescription: "Tratamos enfermedades respiratorias en Houston TX incluyendo gripe, resfriado, bronquitis, sinusitis, asma y COVID-19. Nuestro equipo médico ofrece diagnóstico rápido con pruebas disponibles y tratamiento efectivo para su recuperación.\n\n**Condiciones respiratorias que tratamos:**\n\n- Gripe (influenza) y resfriado común\n- Bronquitis aguda y crónica\n- Sinusitis e infecciones de senos paranasales\n- Asma y crisis asmáticas\n- COVID-19 y sus variantes\n- Neumonía\n- Faringitis y amigdalitis\n- Tos persistente\n\n**Diagnóstico rápido en la clínica**\n\nContamos con pruebas rápidas de influenza y COVID-19 con resultados en minutos. Nuestro médico evaluará sus síntomas, escuchará sus pulmones, y determinará el tratamiento más efectivo para su condición.\n\n**Tratamientos disponibles:**\n\n- Medicamentos antivirales (para gripe y COVID-19 si se detectan a tiempo)\n- Antibióticos (para infecciones bacterianas confirmadas)\n- Nebulizaciones con broncodilatadores\n- Inyecciones de esteroides para inflamación severa\n- Medicamentos para la tos y descongestión\n- Inhaladores para asma\n\n**¿Cuándo debe buscar atención médica?**\n\nVisite nuestra clínica si tiene fiebre alta que no baja con medicamentos, dificultad para respirar, tos con sangre o flema de color verde/amarillo por más de una semana, dolor en el pecho al respirar, o si sus síntomas empeoran después de 3-5 días. La atención temprana previene complicaciones.\n\nAtención sin cita previa en español, con precios accesibles para la comunidad hispana de Houston.",
    titleEn: "Flu & Respiratory Illness Treatment Houston TX",
    descriptionEn: "Treatment for flu, bronchitis, asthma, and COVID-19 in Houston TX. Rapid diagnosis, nebulizer treatments, and on-site testing available.",
    longDescriptionEn: "We treat respiratory illnesses in Houston TX including flu, common cold, bronchitis, sinusitis, asthma, and COVID-19. Our medical team offers rapid diagnosis with on-site testing and effective treatment for your recovery.\n\n**Respiratory conditions we treat:**\n\n- Influenza and common cold\n- Acute and chronic bronchitis\n- Sinusitis and sinus infections\n- Asthma and asthma attacks\n- COVID-19 and its variants\n- Pneumonia\n- Pharyngitis and tonsillitis\n- Persistent cough\n\n**Rapid diagnosis at the clinic**\n\nWe have rapid flu and COVID-19 tests with results in minutes. Our physician will evaluate your symptoms, listen to your lungs, and determine the most effective treatment for your condition.\n\n**Available treatments:**\n\n- Antiviral medications (for flu and COVID-19 when detected early)\n- Antibiotics (for confirmed bacterial infections)\n- Nebulizer treatments with bronchodilators\n- Steroid injections for severe inflammation\n- Cough and decongestant medications\n- Inhalers for asthma\n\n**When should you seek medical care?**\n\nVisit our clinic if you have a high fever that won't break with medication, difficulty breathing, cough with blood or green/yellow phlegm for more than a week, chest pain when breathing, or if your symptoms worsen after 3-5 days. Early care prevents complications.\n\nWalk-in care available, Spanish-language service, affordable pricing for Houston's Hispanic community.",
    icon: "Wind",
    image: "/images/services/respiratory.webp",
    category: "especial",
    keywords: ["enfermedades respiratorias Houston", "gripe Houston", "bronquitis Houston", "COVID Houston", "tratamiento asma Houston"],
    keywordsEn: ["flu treatment Houston TX", "respiratory illness Houston", "bronchitis treatment Houston", "COVID-19 clinic Houston", "asthma treatment Houston"],
    features: [
      "Diagnóstico rápido",
      "Tratamiento de gripe",
      "Bronquitis y sinusitis",
      "Pruebas de COVID-19",
      "Tratamiento de asma",
      "Nebulizaciones disponibles"
    ],
    featuresEn: ["Rapid diagnosis", "Flu treatment", "Bronchitis & sinusitis care", "COVID-19 testing", "Asthma management", "On-site nebulizer treatments"],
    highlighted: false,
    order: 13,
  },
  {
    id: "infecciones-urinarias",
    slug: "infecciones-urinarias",
    title: "Tratamiento Infecciones Urinarias Houston",
    shortTitle: "Urinarias",
    description: "Diagnóstico y tratamiento de infecciones urinarias UTI en Houston TX. Análisis de orina en sitio con resultados y tratamiento inmediato.",
    longDescription: "Diagnosticamos y tratamos infecciones urinarias (UTI) en Houston TX de manera efectiva. Las infecciones del tracto urinario son una de las condiciones más comunes, especialmente en mujeres, y requieren atención médica oportuna para evitar complicaciones.\n\n**Síntomas comunes de infección urinaria:**\n\n- Ardor o dolor al orinar\n- Necesidad frecuente y urgente de ir al baño\n- Orina turbia, oscura o con olor fuerte\n- Dolor en la parte baja del abdomen o espalda\n- Sensación de no vaciar la vejiga completamente\n- Fiebre o escalofríos (puede indicar infección más seria)\n\n**Diagnóstico rápido en la clínica**\n\nRealizamos análisis de orina en el sitio con resultados en minutos. Esto nos permite confirmar la infección, identificar el tipo de bacteria, y prescribir el antibiótico más efectivo el mismo día. No necesita esperar días por resultados de laboratorio externo.\n\n**Tratamiento el mismo día**\n\nUna vez confirmado el diagnóstico, nuestro médico le prescribirá el tratamiento antibiótico adecuado. La mayoría de los pacientes experimentan mejoría significativa dentro de 24-48 horas de iniciar el tratamiento.\n\n**Prevención de infecciones recurrentes**\n\nSi sufre de infecciones urinarias frecuentes, nuestro equipo médico le brindará consejería personalizada sobre medidas preventivas, cambios en hábitos, e hidratación adecuada para reducir la frecuencia de recurrencia.\n\nAtención para hombres y mujeres, sin cita previa, en español. Ubicados en 5705 Fondren Rd STE 101, Houston TX 77036.",
    titleEn: "UTI Urinary Tract Infection Treatment Houston TX",
    descriptionEn: "Diagnosis and treatment of urinary tract infections UTI in Houston TX. On-site urinalysis with same-day results and immediate treatment.",
    longDescriptionEn: "We diagnose and treat urinary tract infections (UTIs) in Houston TX effectively. UTIs are one of the most common conditions, especially in women, and require timely medical care to avoid complications.\n\n**Common UTI symptoms:**\n\n- Burning or pain during urination\n- Frequent and urgent need to urinate\n- Cloudy, dark, or strong-smelling urine\n- Lower abdominal or back pain\n- Feeling of not emptying the bladder completely\n- Fever or chills (may indicate a more serious infection)\n\n**Rapid diagnosis at the clinic**\n\nWe perform on-site urinalysis with results in minutes. This allows us to confirm the infection, identify the type of bacteria, and prescribe the most effective antibiotic the same day. No need to wait days for external lab results.\n\n**Same-day treatment**\n\nOnce the diagnosis is confirmed, our physician will prescribe the appropriate antibiotic treatment. Most patients experience significant improvement within 24-48 hours of starting treatment.\n\n**Preventing recurrent infections**\n\nIf you suffer from frequent UTIs, our medical team will provide personalized counseling on preventive measures, habit changes, and proper hydration to reduce recurrence.\n\nCare for men and women, walk-ins welcome, Spanish-language service. Located at 5705 Fondren Rd STE 101, Houston TX 77036.",
    icon: "Droplet",
    image: "/images/services/urinary-infections.webp",
    category: "especial",
    keywords: ["infección urinaria Houston", "UTI Houston", "cistitis Houston", "tratamiento UTI Houston"],
    keywordsEn: ["UTI treatment Houston TX", "urinary tract infection Houston", "bladder infection Houston", "same-day UTI care Houston", "urinalysis Houston TX"],
    features: [
      "Diagnóstico rápido",
      "Análisis de orina en sitio",
      "Tratamiento el mismo día",
      "Prevención de recurrencia",
      "Hombres y mujeres",
      "Sin cita previa"
    ],
    featuresEn: ["Rapid diagnosis", "On-site urinalysis", "Same-day treatment", "Recurrence prevention guidance", "Care for men & women", "No appointment needed"],
    highlighted: false,
    order: 14,
  },
  {
    id: "infecciones-vaginales",
    slug: "infecciones-vaginales",
    title: "Tratamiento Infecciones Vaginales Houston",
    shortTitle: "Vaginales",
    description: "Diagnóstico y tratamiento confidencial de candidiasis, vaginosis bacteriana y tricomoniasis en Houston TX. Ambiente discreto.",
    longDescription: "Ofrecemos diagnóstico y tratamiento confidencial de infecciones vaginales en Houston TX. Estas condiciones son muy comunes y tratables, pero requieren diagnóstico profesional para recibir el tratamiento correcto.\n\n**Tipos de infecciones vaginales que tratamos:**\n\n- Candidiasis (infección por hongos/levaduras)\n- Vaginosis bacteriana\n- Tricomoniasis\n- Infecciones mixtas\n- Irritación y resequedad vaginal\n\n**Síntomas que debe consultar:**\n\n- Flujo vaginal anormal (cambio en color, olor o cantidad)\n- Picazón o irritación vaginal\n- Ardor al orinar\n- Dolor durante las relaciones\n- Enrojecimiento o hinchazón\n- Olor inusual\n\n**¿Por qué es importante el diagnóstico profesional?**\n\nMuchas mujeres intentan tratar las infecciones vaginales con productos de venta libre sin saber exactamente qué tipo de infección tienen. Los tratamientos para hongos no funcionan contra bacterias, y viceversa. Un diagnóstico correcto asegura el tratamiento efectivo desde el primer día.\n\n**Ambiente discreto y de confianza**\n\nEntendemos que este tema puede ser incómodo de discutir. En Clínica Hispana La Caridad, nuestro equipo médico le atiende con total privacidad, respeto y profesionalismo. La consulta incluye evaluación, diagnóstico, y prescripción de tratamiento. También ofrecemos consejería sobre medidas de prevención para evitar infecciones recurrentes.\n\nAtención confidencial en español, sin cita previa, con precios accesibles en Houston TX.",
    titleEn: "Vaginal Infection Treatment Houston TX",
    descriptionEn: "Confidential diagnosis and treatment of yeast infections, bacterial vaginosis, and trichomoniasis in Houston TX. Discreet and professional care.",
    longDescriptionEn: "We offer confidential diagnosis and treatment of vaginal infections in Houston TX. These conditions are very common and treatable, but require professional diagnosis to receive the correct treatment.\n\n**Types of vaginal infections we treat:**\n\n- Candidiasis (yeast infection)\n- Bacterial vaginosis\n- Trichomoniasis\n- Mixed infections\n- Vaginal irritation and dryness\n\n**Symptoms to watch for:**\n\n- Abnormal vaginal discharge (change in color, odor, or amount)\n- Vaginal itching or irritation\n- Burning during urination\n- Pain during intercourse\n- Redness or swelling\n- Unusual odor\n\n**Why is professional diagnosis important?**\n\nMany women try to treat vaginal infections with over-the-counter products without knowing exactly what type of infection they have. Yeast treatments don't work against bacteria, and vice versa. An accurate diagnosis ensures effective treatment from day one.\n\n**Discreet and trustworthy environment**\n\nWe understand this topic can be uncomfortable to discuss. At Clínica Hispana La Caridad, our medical team treats you with complete privacy, respect, and professionalism. The consultation includes evaluation, diagnosis, and treatment prescription. We also offer counseling on prevention measures.\n\nConfidential care in Spanish, walk-ins welcome, affordable pricing in Houston TX.",
    icon: "ShieldCheck",
    image: "/images/services/vaginal-infections.webp",
    category: "mujer",
    keywords: ["infección vaginal Houston", "candidiasis Houston", "vaginosis Houston", "tratamiento hongos Houston"],
    keywordsEn: ["vaginal infection treatment Houston", "yeast infection Houston TX", "bacterial vaginosis Houston", "BV treatment Houston", "women's health clinic Houston"],
    features: [
      "Diagnóstico confidencial",
      "Tratamiento efectivo",
      "Candidiasis y hongos",
      "Vaginosis bacteriana",
      "Ambiente discreto",
      "Consejería de prevención"
    ],
    featuresEn: ["Confidential diagnosis", "Effective treatment", "Yeast infection & candidiasis care", "Bacterial vaginosis treatment", "Discreet clinical environment", "Prevention counseling"],
    highlighted: false,
    order: 15,
  },
  {
    id: "examen-dot",
    slug: "examen-dot",
    title: "Examen Físico DOT Houston - Licencia CDL",
    shortTitle: "DOT",
    description: "Examen médico DOT en Houston TX para licencia de conducir comercial CDL. Médicos certificados FMCSA, resultados el mismo día.",
    longDescription: "Realizamos exámenes médicos DOT (Department of Transportation) en Houston TX, requeridos para obtener o renovar su licencia de conducir comercial (CDL). Nuestros médicos están certificados por FMCSA y registrados en el National Registry of Certified Medical Examiners.\n\n**¿Qué incluye el examen físico DOT?**\n\n- Examen de visión (agudeza visual y campo visual)\n- Examen de audición\n- Medición de presión arterial y pulso\n- Análisis de orina (proteína, sangre, glucosa)\n- Examen físico general (corazón, pulmones, abdomen, columna)\n- Evaluación neurológica básica\n- Revisión de historial médico y medicamentos\n- Llenado del formulario oficial MCSA-5875\n\n**¿Quién necesita el examen DOT?**\n\nTodo conductor que opera vehículos comerciales que requieren licencia CDL (Clase A, B, o C) debe pasar un examen físico DOT cada 24 meses. Esto incluye conductores de camiones, autobuses, vehículos de transporte de materiales peligrosos, y otros vehículos comerciales.\n\n**Resultados el mismo día**\n\nCompletamos el examen y el formulario oficial en una sola visita. Si cumple con todos los requisitos, recibirá su certificado médico DOT (Medical Examiner's Certificate) el mismo día para que pueda presentarlo inmediatamente al DMV o a su empleador.\n\n**Condiciones que pueden afectar la certificación**\n\nSi tiene diabetes, hipertensión, apnea del sueño, u otra condición crónica, nuestro médico evaluará si cumple con los estándares de FMCSA y le indicará los pasos necesarios. En muchos casos, con documentación adecuada de su médico tratante, puede obtener la certificación.\n\nAtención sin cita previa en español, con precios competitivos en Houston TX.",
    titleEn: "DOT Physical Exam Houston TX - CDL Medical Certificate",
    descriptionEn: "DOT physical exam in Houston TX for commercial driver's license CDL. FMCSA-certified medical examiners, same-day results and official certificate.",
    longDescriptionEn: "We perform DOT (Department of Transportation) physical exams in Houston TX required to obtain or renew your commercial driver's license (CDL). Our physicians are FMCSA-certified and registered in the National Registry of Certified Medical Examiners.\n\n**What does the DOT physical exam include?**\n\n- Vision exam (visual acuity and field of vision)\n- Hearing exam\n- Blood pressure and pulse measurement\n- Urinalysis (protein, blood, glucose)\n- General physical exam (heart, lungs, abdomen, spine)\n- Basic neurological evaluation\n- Medical history and medication review\n- Official MCSA-5875 form completion\n\n**Who needs a DOT physical?**\n\nEvery driver operating commercial vehicles requiring a CDL (Class A, B, or C) must pass a DOT physical every 24 months. This includes truck drivers, bus operators, hazmat transporters, and other commercial vehicle operators.\n\n**Same-day results**\n\nWe complete the exam and official paperwork in a single visit. If you meet all requirements, you'll receive your DOT Medical Examiner's Certificate the same day so you can present it immediately to the DMV or your employer.\n\n**Conditions that may affect certification**\n\nIf you have diabetes, hypertension, sleep apnea, or another chronic condition, our physician will evaluate whether you meet FMCSA standards and guide you through the necessary steps. In many cases, with proper documentation from your treating physician, certification can be obtained.\n\nWalk-ins welcome, Spanish-language service, competitive pricing in Houston TX.",
    icon: "Truck",
    image: "/images/services/dot-exam.webp",
    category: "diagnostico",
    keywords: ["examen DOT Houston", "físico CDL Houston", "examen conductor comercial Houston", "DOT physical Houston"],
    keywordsEn: ["DOT physical Houston TX", "CDL medical exam Houston", "FMCSA physical Houston", "commercial driver physical Houston", "DOT exam same day Houston"],
    features: [
      "Médicos certificados FMCSA",
      "Resultados el mismo día",
      "Formulario oficial DOT",
      "Examen de visión incluido",
      "Precios competitivos",
      "Sin cita previa"
    ],
    featuresEn: ["FMCSA-certified medical examiners", "Same-day results", "Official DOT examination forms", "Vision screening included", "Competitive pricing", "No appointment needed"],
    highlighted: false,
    order: 16,
  },
  {
    id: "examenes-generales",
    slug: "examenes-generales",
    title: "Exámenes Físicos Houston - Trabajo, Escuela, Deportes",
    shortTitle: "Generales",
    description: "Exámenes físicos en Houston TX para empleo, escuela, deportes y chequeo anual. Documentación oficial incluida, resultados rápidos.",
    longDescription: "Realizamos exámenes físicos generales en Houston TX para diversos propósitos. Ya sea que necesite un examen para empleo, escuela, deportes, o simplemente un chequeo anual, nuestro equipo médico le atiende de forma rápida y profesional.\n\n**Tipos de exámenes físicos disponibles:**\n\n- Examen físico para empleo (pre-employment physical)\n- Examen escolar para niños y adolescentes\n- Examen físico deportivo (sports physical)\n- Chequeo anual de rutina\n- Examen para seguro de vida\n- Examen físico para campamentos\n- Certificado médico general\n\n**¿Qué incluye el examen físico?**\n\n- Medición de signos vitales (presión, temperatura, peso, talla)\n- Examen de visión\n- Evaluación cardíaca y pulmonar\n- Examen abdominal\n- Evaluación musculoesquelética\n- Revisión de historial de vacunas\n- Documentación oficial firmada por el médico\n\n**Exámenes para empleo**\n\nMuchos empleadores en Houston requieren un examen físico antes de contratar. Completamos la documentación requerida por su empleador y podemos agregar pruebas de laboratorio o drogas si son necesarias para su posición.\n\n**Exámenes escolares y deportivos**\n\nLas escuelas de Texas requieren exámenes físicos para inscripción y participación en deportes. Realizamos estos exámenes para niños y adolescentes, verificando que estén en condiciones de salud para sus actividades.\n\nDocumentación oficial incluida, resultados rápidos, atención en español, y precios accesibles para toda la familia en Houston TX.",
    titleEn: "Physical Exams Houston TX - Employment, School & Sports",
    descriptionEn: "Physical exams in Houston TX for employment, school, sports, and annual wellness. Official documentation included with fast results.",
    longDescriptionEn: "We perform general physical exams in Houston TX for various purposes. Whether you need an exam for employment, school, sports, or an annual checkup, our medical team provides fast, professional care.\n\n**Types of physical exams available:**\n\n- Pre-employment physical (pre-hire)\n- School physicals for children and teens\n- Sports physical (athletic clearance)\n- Annual wellness checkup\n- Life insurance physical\n- Camp physicals\n- General medical certificate\n\n**What does the physical exam include?**\n\n- Vital signs (blood pressure, temperature, weight, height)\n- Vision screening\n- Heart and lung evaluation\n- Abdominal examination\n- Musculoskeletal assessment\n- Vaccination record review\n- Official documentation signed by physician\n\n**Employment physicals**\n\nMany Houston employers require a physical exam before hiring. We complete your employer's required documentation and can add lab tests or drug screening if needed for your position.\n\n**School and sports physicals**\n\nTexas schools require physical exams for enrollment and sports participation. We perform these exams for children and teenagers, verifying they are in good health for their activities.\n\nOfficial documentation included, fast results, Spanish-language service, affordable pricing for the whole family in Houston TX.",
    icon: "ClipboardCheck",
    image: "/images/services/general-exams.webp",
    category: "diagnostico",
    keywords: ["examen físico Houston", "físico laboral Houston", "examen escolar Houston", "chequeo médico Houston"],
    keywordsEn: ["physical exam Houston TX", "employment physical Houston", "school physical Houston", "sports physical Houston", "annual check-up Houston TX"],
    features: [
      "Exámenes para empleo",
      "Exámenes escolares",
      "Exámenes deportivos",
      "Chequeo anual completo",
      "Documentación oficial",
      "Resultados rápidos"
    ],
    featuresEn: ["Employment physicals", "School physicals", "Sports physicals", "Annual wellness exams", "Official documentation included", "Fast same-visit results"],
    highlighted: false,
    order: 17,
  },
  {
    id: "dolores-musculares",
    slug: "dolores-musculares",
    title: "Tratamiento Dolor de Espalda y Muscular Houston",
    shortTitle: "Musculares",
    description: "Evaluación y tratamiento de dolor muscular, articular y de espalda en Houston TX. Inyecciones disponibles y referencia a terapia física.",
    longDescription: "Ofrecemos evaluación completa y tratamiento del dolor muscular y articular en Houston TX. El dolor de espalda, cuello y articulaciones es una de las causas más comunes de consulta médica y puede afectar significativamente su calidad de vida y capacidad de trabajo.\n\n**Condiciones que evaluamos y tratamos:**\n\n- Dolor de espalda baja (lumbalgia)\n- Dolor de cuello y cervical\n- Dolor de hombros\n- Dolor de rodillas\n- Dolor articular general\n- Espasmos musculares\n- Ciática (dolor que baja por la pierna)\n- Lesiones musculares por trabajo o ejercicio\n- Artritis y dolor articular crónico\n\n**¿Qué incluye la evaluación?**\n\nNuestro médico realizará un examen físico detallado de la zona afectada, evaluará su rango de movimiento, y determinará la causa del dolor. Si es necesario, se ordenarán estudios adicionales como radiografías o ultrasonido para un diagnóstico más preciso.\n\n**Opciones de tratamiento:**\n\n- Medicamentos antiinflamatorios y relajantes musculares\n- Inyecciones para alivio del dolor (trigger points)\n- Terapia con calor o frío\n- Recomendaciones de ejercicios y estiramientos\n- Referencia a terapia física\n- Referencia a ortopedista si es necesario\n\n**¿Cuándo debe buscar atención?**\n\nConsulte si el dolor persiste más de una semana, le impide trabajar o dormir, se acompaña de entumecimiento o debilidad, o es resultado de una lesión o accidente. La evaluación temprana puede prevenir que el dolor se vuelva crónico.\n\nAtención en español, sin cita previa, con precios accesibles en Houston TX.",
    titleEn: "Muscle & Back Pain Treatment Houston TX",
    descriptionEn: "Evaluation and treatment of muscle, joint, and back pain in Houston TX. Injections available and referrals to physical therapy when needed.",
    longDescriptionEn: "We offer comprehensive evaluation and treatment for muscle and joint pain in Houston TX. Back pain, neck pain, and joint issues are among the most common reasons for medical visits and can significantly affect your quality of life and ability to work.\n\n**Conditions we evaluate and treat:**\n\n- Lower back pain (lumbalgia)\n- Neck and cervical pain\n- Shoulder pain\n- Knee pain\n- General joint pain\n- Muscle spasms\n- Sciatica (pain radiating down the leg)\n- Work or exercise-related muscle injuries\n- Arthritis and chronic joint pain\n\n**What does the evaluation include?**\n\nOur physician will perform a detailed physical exam of the affected area, assess your range of motion, and determine the cause of your pain. If needed, additional studies such as X-rays or ultrasound will be ordered for a more precise diagnosis.\n\n**Treatment options:**\n\n- Anti-inflammatory medications and muscle relaxants\n- Pain relief injections (trigger points)\n- Heat or cold therapy\n- Exercise and stretching recommendations\n- Physical therapy referral\n- Orthopedic referral if needed\n\n**When should you seek care?**\n\nConsult if pain persists more than a week, prevents you from working or sleeping, is accompanied by numbness or weakness, or results from an injury or accident. Early evaluation can prevent pain from becoming chronic.\n\nSpanish-language service, walk-ins welcome, affordable pricing in Houston TX.",
    icon: "Bone",
    image: "/images/services/muscle-pain.webp",
    category: "especialidad",
    keywords: ["dolor muscular Houston", "dolor espalda Houston", "dolor articular Houston", "tratamiento dolor Houston"],
    keywordsEn: ["back pain treatment Houston TX", "muscle pain clinic Houston", "joint pain Houston TX", "pain management Houston", "neck pain treatment Houston"],
    features: [
      "Evaluación completa",
      "Tratamiento del dolor",
      "Dolor de espalda y cuello",
      "Dolor articular",
      "Inyecciones disponibles",
      "Referencia a terapia física"
    ],
    featuresEn: ["Complete pain evaluation", "Targeted pain treatment", "Back & neck pain management", "Joint pain assessment", "Pain relief injections available", "Physical therapy referrals"],
    highlighted: false,
    order: 18,
  },
];

export const PROMOTIONS: Promotion[] = [
  {
    id: "consulta-general",
    title: "Consulta Médica General",
    badge: "Más Popular",
    description: "Evaluación médica completa con nuestros especialistas.",
    includes: [
      "Examen físico completo",
      "Revisión de signos vitales",
      "Diagnóstico profesional",
      "Receta médica si es necesario",
    ],
  },
  {
    id: "paquete-diabetes",
    title: "Paquete Control Diabetes",
    badge: "Ahorre $50",
    description: "Todo lo necesario para mantener su diabetes bajo control.",
    includes: [
      "Consulta médica",
      "Examen de glucosa en ayunas",
      "Hemoglobina A1C",
      "Plan de alimentación",
    ],
  },
  {
    id: "chequeo-completo",
    title: "Chequeo Completo",
    badge: "Recomendado",
    description: "Evaluación integral de su estado de salud.",
    includes: [
      "Examen físico completo",
      "Panel de laboratorio básico",
      "Revisión de presión y glucosa",
      "Recomendaciones personalizadas",
    ],
  },
];

export const FAQ_ITEMS: FAQItem[] = [
  {
    id: "cita-previa",
    question: "faq.q1",
    answer: "faq.a1",
  },
  {
    id: "sin-seguro",
    question: "faq.q2",
    answer: "faq.a2",
  },
  {
    id: "espanol",
    question: "faq.q3",
    answer: "faq.a3",
  },
  {
    id: "horarios",
    question: "faq.q4",
    answer: "faq.a4",
  },
  {
    id: "formas-pago",
    question: "faq.q5",
    answer: "faq.a5",
  },
  {
    id: "planes-pago",
    question: "faq.q6",
    answer: "faq.a6",
  },
  {
    id: "ubicacion-houston",
    question: "faq.q7",
    answer: "faq.a7",
  },
  {
    id: "examen-inmigracion",
    question: "faq.q8",
    answer: "faq.a8",
  },
  {
    id: "tiempo-espera",
    question: "faq.q9",
    answer: "faq.a9",
  },
  {
    id: "estacionamiento",
    question: "faq.q10",
    answer: "faq.a10",
  },
];

export const NAV_ITEMS = [
  { label: "nav.services", href: "/services" },
  { label: "nav.greenCard", href: "/#green-card" },
  { label: "nav.blog", href: "/blog" },
  { label: "nav.contact", href: "/#contact" },
];

